/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ece651;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;

import org.junit.jupiter.api.Test;

class AppTest {
  private final InputStream systemIn = System.in;
 
  private ByteArrayInputStream testIn;
  
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }


    private void provideInput(String data) {
        testIn = new ByteArrayInputStream(data.getBytes());
        System.setIn(testIn);
    }


    @Test
    public void testCase() throws IOException{

      InputStream is = new FileInputStream("./input.txt");
      BufferedReader buf = new BufferedReader(new InputStreamReader(is));
      String line = buf.readLine();
      StringBuilder sb = new StringBuilder();
      while(line != null){
        sb.append(line).append("\n");
        line = buf.readLine();
      }
      provideInput(sb.toString());
      App.main(new String[0]);
      
      is = new FileInputStream("./input2.txt");
      buf = new BufferedReader(new InputStreamReader(is));
      line = buf.readLine();
      sb = new StringBuilder();
      while(line != null){
        sb.append(line).append("\n");
        line = buf.readLine();
      }
      provideInput(sb.toString());
      App.main(new String[0]);
    }
}
